//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.20 at 01:08:36 PM PDT 
//


package net.systemsbiology.regis_web.pepxml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mixtureModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mixtureModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="point" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="pos_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="neg_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="neg_obs_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                 &lt;attribute name="pos_obs_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pos_bandwidth" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="neg_bandwidth" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mixtureModelType", propOrder = {
    "point"
})
public class MixtureModelType {

    protected List<MixtureModelType.Point> point;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "pos_bandwidth", required = true)
    protected BigDecimal posBandwidth;
    @XmlAttribute(name = "neg_bandwidth", required = true)
    protected BigDecimal negBandwidth;

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MixtureModelType.Point }
     * 
     * 
     */
    public List<MixtureModelType.Point> getPoint() {
        if (point == null) {
            point = new ArrayList<MixtureModelType.Point>();
        }
        return this.point;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the posBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPosBandwidth() {
        return posBandwidth;
    }

    /**
     * Sets the value of the posBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPosBandwidth(BigDecimal value) {
        this.posBandwidth = value;
    }

    /**
     * Gets the value of the negBandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNegBandwidth() {
        return negBandwidth;
    }

    /**
     * Sets the value of the negBandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNegBandwidth(BigDecimal value) {
        this.negBandwidth = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="pos_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="neg_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="neg_obs_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *       &lt;attribute name="pos_obs_dens" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Point {

        @XmlAttribute(name = "value")
        protected BigDecimal value;
        @XmlAttribute(name = "pos_dens")
        protected BigDecimal posDens;
        @XmlAttribute(name = "neg_dens")
        protected BigDecimal negDens;
        @XmlAttribute(name = "neg_obs_dens")
        protected BigDecimal negObsDens;
        @XmlAttribute(name = "pos_obs_dens")
        protected BigDecimal posObsDens;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the posDens property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPosDens() {
            return posDens;
        }

        /**
         * Sets the value of the posDens property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPosDens(BigDecimal value) {
            this.posDens = value;
        }

        /**
         * Gets the value of the negDens property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getNegDens() {
            return negDens;
        }

        /**
         * Sets the value of the negDens property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setNegDens(BigDecimal value) {
            this.negDens = value;
        }

        /**
         * Gets the value of the negObsDens property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getNegObsDens() {
            return negObsDens;
        }

        /**
         * Sets the value of the negObsDens property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setNegObsDens(BigDecimal value) {
            this.negObsDens = value;
        }

        /**
         * Gets the value of the posObsDens property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPosObsDens() {
            return posObsDens;
        }

        /**
         * Sets the value of the posObsDens property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPosObsDens(BigDecimal value) {
            this.posObsDens = value;
        }

    }

}
